# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: ServerCICD
on:
  push:
  pull_request:
    branches: 
      - main
      - dev
      
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x] # 개발환경과 동일하게 맞춤
        
    steps:
      # 브랜치에 checkout해 코드를 가져온다
      - name: Checkout source code. 
        uses: actions/checkout@v2
        
      # node 설치 및 버전 확인한다.
      - name: Node.js ${{ matrix.node-version }} install
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Check Npm -v
        run: npm -v 

        # npm ci를 통해 npm install 진행
      - name: npm CI
        run: npm ci
        
        #lint 통과 확인
      - name: check ESLint
        run: npm run lint
        
        # CI 통과 시 build하여 server.js 파일 생성
      - name: run build (main <- dev)
        if: ${{ github.ref == 'refs/heads/main' }} 
        run: npm run build:production --if-present
        
      - name: run build (dev <- *)
        run: npm run build --if-present


#   deploy:
#     needs: build
#     runs-on: ubuntu-latest
#     steps:  
      #CD
      # build 파일을 ec2에 올리기
#       - name: build file upload to ec2 
#         uses: garygrossgarten/github-action-scp@release
#         with:
#             local: ./dist
#             remote: /home/ubuntu/server-wishboard/dist/
#             host: ${{ secrets.REMOTE_IP }}
#             username: ${{ secrets.REMOTE_SSH_ID }}
#             privateKey: ${{ secrets.REMOTE_SSH_PK }}
#             port: ${{ secrets.REMOTE_SSH_PORT }}
#             recursive: true
#       - name: ec2 update
#         uses: appleboy/ssh-action@master
#         with:
#            host: ${{ secrets.REMOTE_IP }}
#            username: ${{ secrets.REMOTE_SSH_ID }}
#            key: ${{ secrets.REMOTE_SSH_PK }}
#            script: pm2 restart 0 --update-env
